'use client';

import React, { useState } from 'react';
import Badge from '@/components/ui/Badge';
import { Download, Trash2, Search } from 'lucide-react';
import { toast } from 'sonner';
import Modal from '@/components/ui/Modal';

// Backend integration point: replace with GET /api/reports/exports?limit=10
const exportHistory = [
  { id: 'exp-2026-081', name: 'Executive Summary — Q3 2026', template: 'Executive Summary', format: 'PDF', size: '2.4 MB', run: 'run-2026-041', generatedBy: 'Marcus Rivera', ts: 'Jul 28, 14:48', status: 'complete' },
  { id: 'exp-2026-080', name: 'Segment Deep-Dive — Jul 28', template: 'Segment Deep-Dive', format: 'XLSX', size: '1.8 MB', run: 'run-2026-041', generatedBy: 'Priya Sharma', ts: 'Jul 28, 11:22', status: 'complete' },
  { id: 'exp-2026-079', name: 'Model Accuracy — run-040', template: 'Model Accuracy Report', format: 'PDF', size: '3.1 MB', run: 'run-2026-040', generatedBy: 'Keiko Tanaka', ts: 'Jul 27, 16:05', status: 'complete' },
  { id: 'exp-2026-078', name: 'EMEA Deep-Dive', template: 'Segment Deep-Dive', format: 'CSV', size: '840 KB', run: 'run-2026-038', generatedBy: 'Lena Hoffmann', ts: 'Jul 25, 09:31', status: 'complete' },
  { id: 'exp-2026-077', name: 'Weekly Board Pack', template: 'Executive Summary', format: 'PDF', size: '—', run: 'run-2026-037', generatedBy: 'System', ts: 'Jul 22, 07:00', status: 'error' },
  { id: 'exp-2026-076', name: 'Q2 Backtest Analysis', template: 'Model Accuracy Report', format: 'PDF', size: '2.9 MB', run: 'run-2026-036', generatedBy: 'Marcus Rivera', ts: 'Jul 18, 16:35', status: 'complete' },
  { id: 'exp-2026-075', name: 'Category Performance', template: 'Segment Deep-Dive', format: 'XLSX', size: '1.4 MB', run: 'run-2026-035', generatedBy: 'Priya Sharma', ts: 'Jul 15, 10:18', status: 'complete' },
  { id: 'exp-2026-074', name: 'India Pilot Report', template: 'Executive Summary', format: 'PDF', size: '1.9 MB', run: 'run-2026-034', generatedBy: 'Keiko Tanaka', ts: 'Jul 10, 14:30', status: 'complete' },
  { id: 'exp-2026-073', name: 'H1 2026 Review', template: 'Segment Deep-Dive', format: 'PDF', size: '4.2 MB', run: 'run-2026-030', generatedBy: 'Marcus Rivera', ts: 'Jul 05, 09:00', status: 'complete' },
  { id: 'exp-2026-072', name: 'Jun Accuracy Check', template: 'Model Accuracy Report', format: 'CSV', size: '620 KB', run: 'run-2026-028', generatedBy: 'Lena Hoffmann', ts: 'Jun 30, 16:45', status: 'complete' },
];

export default function ExportHistoryTable() {
  const [search, setSearch] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);

  const filtered = exportHistory.filter(
    (e) =>
      e.name.toLowerCase().includes(search.toLowerCase()) ||
      e.template.toLowerCase().includes(search.toLowerCase()) ||
      e.generatedBy.toLowerCase().includes(search.toLowerCase())
  );

  const handleDelete = (id: string) => {
    setDeleteTarget(null);
    // Backend integration point: DELETE /api/reports/exports/:id
    toast.success('Export record deleted');
  };

  return (
    <div className="card-elevated overflow-hidden">
      <div className="px-5 py-4 flex items-center justify-between gap-4" style={{ borderBottom: '1px solid var(--border)' }}>
        <div>
          <h2 className="text-base font-semibold text-foreground">Export History</h2>
          <p className="text-xs mt-0.5" style={{ color: 'var(--muted-foreground)' }}>
            {filtered.length} of {exportHistory.length} exports
          </p>
        </div>
        <div className="relative">
          <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: 'var(--muted-foreground)' }} />
          <input
            type="text"
            placeholder="Search exports…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="input-field pl-8 h-8 text-xs w-48"
          />
        </div>
      </div>

      <div className="overflow-x-auto scrollbar-thin">
        <table className="w-full text-sm">
          <thead>
            <tr style={{ background: 'var(--muted)' }}>
              {['Report Name', 'Template', 'Format', 'Size', 'Run', 'Generated By', 'Date', 'Status', ''].map((h) => (
                <th key={`eh-h-${h}`} className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide whitespace-nowrap"
                  style={{ color: 'var(--muted-foreground)' }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.map((row, i) => (
              <tr
                key={row.id}
                className="transition-colors duration-100"
                style={{
                  background: i % 2 === 0 ? 'var(--card)' : 'var(--secondary)',
                  borderBottom: '1px solid var(--border)',
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--muted)')}
                onMouseLeave={(e) => (e.currentTarget.style.background = i % 2 === 0 ? 'var(--card)' : 'var(--secondary)')}
              >
                <td className="px-4 py-3 font-medium text-foreground max-w-[200px]">
                  <p className="truncate">{row.name}</p>
                </td>
                <td className="px-4 py-3 whitespace-nowrap">
                  <span className="text-xs" style={{ color: 'var(--muted-foreground)' }}>{row.template}</span>
                </td>
                <td className="px-4 py-3">
                  <span className="font-mono text-xs px-2 py-0.5 rounded" style={{ background: 'var(--muted)', color: 'var(--foreground)' }}>
                    {row.format}
                  </span>
                </td>
                <td className="px-4 py-3 font-mono text-xs tabular-nums" style={{ color: 'var(--muted-foreground)' }}>{row.size}</td>
                <td className="px-4 py-3 font-mono text-xs" style={{ color: 'var(--primary)' }}>{row.run}</td>
                <td className="px-4 py-3 text-xs whitespace-nowrap" style={{ color: 'var(--muted-foreground)' }}>{row.generatedBy}</td>
                <td className="px-4 py-3 font-mono text-xs whitespace-nowrap" style={{ color: 'var(--muted-foreground)' }}>{row.ts}</td>
                <td className="px-4 py-3">
                  <Badge variant={row.status as any} dot>{row.status}</Badge>
                </td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"
                    style={{ opacity: 1 }}>
                    {row.status === 'complete' && (
                      <button
                        className="btn-ghost h-7 w-7 p-0 justify-center"
                        title="Download export"
                        onClick={() => toast.success(`Downloading ${row.name}`)}
                      >
                        <Download size={13} />
                      </button>
                    )}
                    <button
                      className="btn-ghost h-7 w-7 p-0 justify-center"
                      title="Delete export record"
                      onClick={() => setDeleteTarget(row.id)}
                      style={{ color: 'var(--negative)' }}
                    >
                      <Trash2 size={13} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Delete Confirm Modal */}
      <Modal
        open={deleteTarget !== null}
        onClose={() => setDeleteTarget(null)}
        title="Delete Export Record"
        size="sm"
      >
        <p className="text-sm mb-6" style={{ color: 'var(--muted-foreground)' }}>
          This will permanently delete the export record and remove the download link. The underlying forecast data will not be affected.
        </p>
        <div className="flex justify-end gap-3">
          <button onClick={() => setDeleteTarget(null)} className="btn-ghost">Cancel</button>
          <button onClick={() => handleDelete(deleteTarget!)} className="btn-danger">Delete Record</button>
        </div>
      </Modal>
    </div>
  );
}